# Generated by Django 4.1.7 on 2023-05-04 22:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MenuApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='menu_name',
            field=models.CharField(max_length=255, verbose_name='Меню:'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Имя:'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_parent', to='MenuApp.menu', verbose_name='Подпункт в меню:'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True, verbose_name='URL'),
        ),
    ]
