# Generated by Django 4.1.7 on 2023-05-04 22:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MenuApp', '0002_alter_menu_menu_name_alter_menu_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_parent', to='MenuApp.menu', verbose_name='Подпункт для:'),
        ),
    ]
