# Generated by Django 4.1.7 on 2023-05-04 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MenuApp', '0003_alter_menu_parent'),
    ]

    operations = [
        migrations.AlterOrderWithRespectTo(
            name='menu',
            order_with_respect_to='menu_name',
        ),
    ]
