# Generated by Django 4.1.7 on 2023-05-05 03:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MenuApp', '0004_alter_menu_order_with_respect_to'),
    ]

    operations = [
        migrations.AlterOrderWithRespectTo(
            name='menu',
            order_with_respect_to=None,
        ),
    ]
