# Generated by Django 4.1.7 on 2023-05-05 06:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MenuApp', '0005_alter_menu_order_with_respect_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='MenuApp.menu', verbose_name='Подпункт для:'),
        ),
    ]
